### CODE 模式 ###

### 获取CODE
GET {{auth-server}}/oauth2/authorize
Content-Type: application/x-www-form-urlencoded
#Authorization: Basic {{username}} {{password}}

grant_type=authorization_code&response_type=code&client_id=messaging-client&scope=message.read%20message.write&redirect_uri=http://127.0.0.1:8080/authorized

> {% client.global.set("code",response.headers.valueOf("Location").split("code=")[1])%}

### 获取TOKEN
POST {{auth-server}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Accept: */*

&scope=all&grant_type=authorization_code&code={{code}}&username=admin&password=test&client_id=hello&client_secret=test&redirect_uri=http://localhost

> {% client.global.set("token", response.body.access_token); %}

### scope=message.read%20message.write&state=eDusiI8AlcxXo8VuT5pBIhk33xeR9H0ZXPTpjxrHlOY%3D&redirect_uri=http://127.0.0.1:8080/authorized
###
POST {{auth-server}}/login/oauth2/password/messaging-password
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{username}} {{password}}

grant_type=password&client_id=messaging-client&client_secret=secret

### 获取用户信息
GET {{auth-server}}/me
Authorization: bearer {{token}}

